on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Echo Go version
        run: go version

      - name: build
        run: scripts/buildprod.sh

      - name: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'Build and submit'
        run: 'gcloud builds submit --tag europe-west2-docker.pkg.dev/notely-405517/notely-ar-repo/notely:latest .'

      - name: 'Make migration'
        run: './scripts/migrateup.sh'

      - name: 'Deploy to Cloud Run'
        run: 'gcloud run deploy notely --image europe-west2-docker.pkg.dev/notely-405517/notely-ar-repo/notely:latest --region us-central1 --allow-unauthenticated --project notely-405517 --max-instances=4'
